services:
  # Base de datos PostgreSQL para n8n y nuestro Backend
  postgres:
    image: postgres:15-alpine
    container_name: sysops-postgres
    restart: always
    environment:
      POSTGRES_USER: sysops_user
      POSTGRES_PASSWORD: sysops_password
      POSTGRES_DB: sysops_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sysops-net

  # Motor de Automatización n8n
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: sysops-n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - sysops-net

  # --- BACKEND (API Express + Watchdog) ---
  api:
    build:
      context: ../apps/api
      dockerfile: Dockerfile
    container_name: sysops-api
    restart: always
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DOCKER_SOCKET_PATH=/var/run/docker.sock
      # Usamos el nombre del servicio 'sysops-n8n' gracias a la red interna
      - N8N_WEBHOOK_URL=http://sysops-n8n:5678/webhook/container-alert
    volumes:
      # Permitir que el backend controle Docker dentro del servidor Ubuntu
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - n8n
      - postgres
    networks:
      - sysops-net

  # --- FRONTEND (Dashboard Web) ---
  web:
    build:
      context: ../apps/web
      dockerfile: Dockerfile
    container_name: sysops-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://192.168.18.82:3001
    depends_on:
      - api
    networks:
      - sysops-net

# --- RED INTERNA CUSTOM Y VOLÚMENES ---
networks:
  sysops-net:
    driver: bridge

volumes:
  postgres_data:
  n8n_data: